#!/usr/bin/env python

import argparse
import praw


def main():

    parser = argparse.ArgumentParser(
        description="Look for a word in your own submissions"
    )
    parser.add_argument("word", help="Word to look for")
    args = parser.parse_args()
    reddit = praw.Reddit("bot1", user_agent="organizer by /u/jbrr25")
    print(reddit.user.me())

    for comment in reddit.user.me().comments.new(limit=None):
        if args.word in comment.body:
            print(f"\n{comment.submission.subreddit} - {comment.submission.title}")
            print(comment.body)
            print("-" * 40)


if __name__ == "__main__":
    main()
