#!/usr/bin/env python

import pandas as pd
import requests
import time
from collections import Counter
from typing import List


def counter_str(counter: Counter) -> str:
    return ", ".join([f"{n}: {q}" for n, q in counter.most_common()])


def get_animes() -> List[str]:
    animes = []
    with open("animes", "r") as f:
        for line in f:
            if not line.startswith("#"):
                animes.append(line.strip())
    return animes


base_url = 'https://graphql.anilist.co'

animes = get_animes()

cols = ["Original Name", "Name", "Genres"]
c = Counter()

data = []
query = '''
query ($name: String) {
  Media (search: $name, type: ANIME) {
    id
    title {
      english
      romaji
    }
    genres
  }
}
'''

max_str_length = 0
for anime in animes:
    message = f"Getting info for: {anime}"
    if len(message) > max_str_length:
        max_str_length = len(message)
    message = message.ljust(max_str_length)
    print(message, end="\r")

    variables = {"name": anime}

    r = requests.post(base_url, json={'query': query, 'variables': variables})
    res = r.json()["data"]["Media"]
    s = [res["title"]["romaji"], res["title"]["english"], ", ".join([x for x in res["genres"]])]
    c.update(res["genres"])
    data.append(s)
    time.sleep(0.7)

print(" " * max_str_length, end="\r")
df = pd.DataFrame(columns=cols, data=data)

print(df)

print(counter_str(c))
