#!/usr/bin/env python

import praw
import argparse


def main():
    parser = argparse.ArgumentParser(
        description="Downloads the upvoted posts of the specified subreddit"
    )
    parser.add_argument("subreddit")
    args = parser.parse_args()

    subreddit = args.subreddit

    reddit = praw.Reddit("bot1", user_agent="organizer by /u/jbrr25")
    print(reddit.user.me())

    upvoted = reddit.user.me().upvoted(limit=None)
    with open(f"{subreddit}.txt", "w") as f:
        for post in upvoted:
            if post.subreddit == subreddit:
                f.write(
                    f"{post.title} - {post.url} - https://www.reddit.com{post.permalink}\n"
                )


if __name__ == "__main__":
    main()
